points_multipliers:
  Visual_Novel: 0.0028571428571429 # Characters
  Manga: 0.25 # Pages
  Anime: 13.0 # Episodes
  Book: 1.0 # Pages
  Reading_Time: 0.67 # Minutes
  Listening_Time: 0.67 # Minutes
  Reading: 0.0028571428571429 # Characters

immersion_bot:
  allowed_log_channels:
    - 814947177608118273
    - 1297383003479081017

achievements:
  Visual Novel:
    - points: 1
      title: "ğŸŒ± Prologue Student"
      description: "You took your first steps into the world of visual novels. Countless stories are waiting for you, one click at a time! ğŸŒ±"
    - points: 250
      title: "ğŸƒ Common Route Explorer"
      description: "Your travel is just getting started. You're in the common route, but soon things will open up as you grow! ğŸƒ"
    - points: 600
      title: "ğŸŒ¿ Route Navigator"
      description: "You're beginning to understand relationships and making the right choices! ğŸŒ¿"
    - points: 1200
      title: "ğŸŒ¸ Love Pursuer"
      description: "Your relationships are blooming, soon common dialogue patterns will no longer have any secrets for you! ğŸŒ¸"
    - points: 4200
      title: "ğŸŒº Garden Keeper"
      description: "You've gone through several routes and can now grasp the nuances in different characters! ğŸŒº"
    - points: 22000
      title: "ğŸ’ Story Enthusiast"
      description: "You've gone through several works, each one increasing your understanding of the language! ğŸ’"
    - points: 40000
      title: "ğŸŒ³ Narrative Sage"
      description: "Complex plots and character developments no longer have secrets for you! ğŸŒ³"
    - points: 300000
      title: "ğŸ‘‘ Tale Keeper"
      description: "With so many works under your belt, you can now read anything you desire! ğŸ‘‘"
    - points: 600000
      title: "ğŸŒ Harem Master"
      description: "You've conquered each world and took everything they had to offer. Few can say the same! ğŸŒ"

  Manga:
    - points: 1
      title: "ğŸ“– Panel Student"
      description: "You took your first steps into the world of mangas. Countless stories are waiting for you, one page at a time! ğŸ“–"
    - points: 150
      title: "ğŸ’¬ Page Explorer"
      description: "Page by page, your understanding grows! ğŸ’¬"
    - points: 400
      title: "ğŸ“‘ Chapter Navigator"
      description: "With each chapter you finish reading, you begin to feel more confident! ğŸ“‘"
    - points: 750
      title: "ğŸ“˜ Volume Voyager"
      description: "First you were counting the chapters, now it's entire volumes in no time! ğŸ“˜"
    - points: 3000
      title: "ğŸ“œ Manga Scholar"
      description: "You're starting to reach out into more complex narratives, churning through the pages at great speed! ğŸ“œ"
    - points: 15000
      title: "ğŸ“š Series Enthusiast"
      description: "You're no longer afraid to start reading longer series, and you begin to enjoy more intricate plots! ğŸ“š"
    - points: 30000
      title: "ğŸ“— Manga Sage"
      description: "Even the manga pages loaded with text are no longer a problem for you, and you even enjoy them! ğŸ“—"
    - points: 225000
      title: "ğŸ‘‘ Bubble Keeper"
      description: "With so many works under your belt, you can now read anything you desire! ğŸ‘‘"
    - points: 450000
      title: "ğŸŒ Doujin Master"
      description: "The world of mangas no longer has any secrets for you, you've explored everything, even the most obscure doujinshis! ğŸŒ"

  Anime:
    - points: 1
      title: "ğŸ“¼ Episode Student"
      description: "You took your first steps into the world of anime. Countless stories are waiting for you, one episode at a time! ğŸ“¼"
    - points: 400
      title: "ğŸ“º Series Explorer"
      description: "You've finished your first series and getting used to speech! ğŸ“º"
    - points: 1000
      title: "ğŸ¬ Anime Navigator"
      description: "Watching through different anime, you're getting familiar with the many tropes! ğŸ¬"
    - points: 2000
      title: "ğŸ—¨ï¸ SOL Specialist"
      description: "You've grasped all the secrets of slice of life, listening to it feels natural! ğŸ—¨ï¸"
    - points: 4000
      title: "ğŸŒ¸ Genre Bloomer"
      description: "You're beginning to seek new, more complex genres to get into! ğŸŒ¸"
    - points: 20000
      title: "ğŸ™ Trope Enthusiast"
      description: "You can tell what each archetype of character is by the way they talk! ğŸ™"
    - points: 40000
      title: "ğŸ‰ Animation Sage"
      description: "The images flow into your brain endlessly, you're not afraid to tackle even the hardest of animes. ğŸ‰"
    - points: 200000
      title: "ğŸ‘‘ Sakuga Keeper"
      description: "You've long forsaken subtitles, instead, the animation speaks to you directly! ğŸ‘‘"
    - points: 400000
      title: "ğŸŒ Otaku Master"
      description: "You've seen it all, yet you constantly seek new thrills. Your knowledge is infinite, share it wisely! ğŸŒ"

  Listening:
    - points: 1
      title: "ğŸµ Mora Student"
      description: "You took your first steps into the world of listening, your ears are just getting warmed up! ğŸµ"
    - points: 400
      title: "ğŸ¶ Dialogue Explorer"
      description: "With a few videos under your belt, you're starting to recognize patterns! ğŸ¶"
    - points: 1000
      title: "ğŸ¼ Audio Navigator"
      description: "You're getting familiar with the language, distinguishing each syllabes clearly. ğŸ¼"
    - points: 2000
      title: "ğŸˆ Word Seeker"
      description: "You begin to understand many words without having to look at subtitles! ğŸˆ"
    - points: 4000
      title: "ğŸ’¬ Speech Specialist"
      description: "You begin to understand natural spoken language with little efforts! ğŸ’¬"
    - points: 20000
      title: "ğŸ¤ Dialect Enthusiast"
      description: "The Tokyo dialect has no secrets for you, and you're exploring the other dialects! ğŸ¤"
    - points: 40000
      title: "ğŸ—« Conversation Sage"
      description: "You can understand conversations between several natives with ease! ğŸ—«"
    - points: 200000
      title: "ğŸ‘‘ Sound Keeper"
      description: "You've long forsaken subtitles, listening to Japanese feels like second nature to you! ğŸ‘‘"
    - points: 400000
      title: "ğŸŒ Listening Master"
      description: "You've achieved perfect harmony with the Japanese language. Even the fastest speaker can't throw you off! ğŸŒ"

  Reading:
    - points: 1
      title: "ğŸˆ´ Moji Student"
      description: "You took your first steps into the world of reading. Countless stories are waiting for you, one character at a time! ğŸˆ´"
    - points: 120
      title: "ğŸ” Page Explorer"
      description: "With each page you read, your understanding grows! ğŸ”"
    - points: 300
      title: "ğŸ“° Chapter Explorer"
      description: "You've finished multiple chapters and begin to follow along the narrative! ğŸ“°"
    - points: 600
      title: "ğŸ“˜ Volume Voyager"
      description: "You've finished your first book and already starting your next! ğŸ“˜"
    - points: 2000
      title: "ğŸ“š SOL Specialist"
      description: "Reading Slice of Life feels natural to you, and you begin to explore new, more complex genres! ğŸ“š"
    - points: 10000
      title: "ğŸ“œ Story Enthusiast"
      description: "With each new author you read, your mastery of the language grows! ğŸ“œ"
    - points: 20000
      title: "ğŸ“• Literary Sage"
      description: "Your literary skills are wide, and you're no longer afraid of more complex novels! ğŸ“•"
    - points: 300000
      title: "ğŸ‘‘ Script Keeper"
      description: "You're reading like a native, you can enjoy even the most intricate storylines! ğŸ‘‘"
    - points: 600000
      title: "ğŸŒ Novel Master"
      description: "You're reading ancient japanese scrolls for fun, share your kanji knowledge with the world! ğŸŒ"
