points_multipliers:
  Visual_Novel: 0.0028571428571429 # Characters
  Manga: 0.25 # Pages
  Anime: 13.0 # Episodes
  Book: 1.0 # Pages
  Reading_Time: 0.67 # Minutes
  Listening_Time: 0.67 # Minutes
  Reading: 0.0028571428571429 # Characters

immersion_bot:
  allowed_log_channels:
    - 814947177608118273
    - 1297383003479081017

achievements:
  Visual Novel:
    - points: 1
      title: "ğŸŒ¸ Prologue Ponderer"
      description: "You've started your first visual novel, exploring Japanese stories one character at a time! ğŸŒ¸"
    - points: 1000
      title: "ğŸ“ Choice Maker"
      description: "You're making meaningful decisions in the story, picking up key phrases along the way. ğŸ“"
    - points: 5000
      title: "ğŸ’– Route Romantic"
      description: "Deep into different routes, you're grasping dialogue and character subtleties with ease! ğŸ’–"
    - points: 15000
      title: "ğŸ’« Plot Weaver"
      description: "You're a pro, following intricate visual novel storylines and understanding advanced vocabulary! ğŸ’«"
    - points: 30000
      title: "ğŸ‘‘ Ultimate Protagonist"
      description: "Fluent in visual novels, you navigate any storyline, from romance to mystery, with full comprehension! ğŸ‘‘"
    - points: 50000
      title: "âœ¨ Narrative Navigator"
      description: "You have a deep understanding of narrative structures and character development across different visual novels. âœ¨"
    - points: 60000
      title: "ğŸŒ€ Storyline Sage"
      description: "You've mastered multiple routes, understanding complex character motivations and plot intricacies. ğŸŒ€"
    - points: 100000
      title: "ğŸŒŸ Legendary Storyteller"
      description: "You've mastered visual novels of all kinds, understanding every twist and emotional nuance! ğŸŒŸ"
    - points: 200000
      title: "ğŸ‘¾ God of Visual Novels"
      description: "You've ascended to the realm of the divine, weaving together every storyline and character arc with omnipotent comprehension! No narrative escapes your grasp. ğŸ‘¾"

  Manga:
    - points: 1
      title: "ğŸ“œ Page Turner"
      description: "You've opened your first manga, exploring Japanese stories one page at a time! ğŸ“œ"
    - points: 100
      title: "ğŸ“š Chapter Chaser"
      description: "You've made it through multiple chapters, starting to recognize key vocabulary and expressions! ğŸ“š"
    - points: 1000
      title: "ğŸ’¬ Speech Bubble Sage"
      description: "Following dialogue and action, you're understanding manga conversations and emotions. ğŸ’¬"
    - points: 5000
      title: "ğŸŒŒ Panel Prodigy"
      description: "You're handling complex storylines, reading comfortably without constant look-ups! ğŸŒŒ"
    - points: 15000
      title: "ğŸ“– Storyline Specialist"
      description: "You can read through entire volumes, understanding intricate plot details and character growth. ğŸ“–"
    - points: 50000
      title: "âœ¨ Manga Virtuoso"
      description: "You've gained the ability to understand advanced manga storylines and cultural nuances with ease. âœ¨"
    - points: 100000
      title: "ğŸ‘¾ Comic Conqueror"
      description: "You've reached the pinnacle of manga reading, effortlessly understanding every story and cultural detail! ğŸ‘¾"
    - points: 200000
      title: "ğŸŒ€ Manga Deity"
      description: "You are the god of manga, able to see through every panel and page, unraveling every detail with unparalleled divine insight! ğŸŒ€"

  Anime:
    - points: 1
      title: "ğŸ­ Opening Act"
      description: "You've watched your first anime episode, diving into Japanese language and culture! ğŸ­"
    - points: 100
      title: "âœ¨ Anime Samurai"
      description: "You're starting to pick up on key words and common phrases. âœ¨"
    - points: 1000
      title: "ğŸŒ  Genre Guru"
      description: "From shonen to shojo, you're understanding a variety of anime genres with growing comprehension! ğŸŒ "
    - points: 10000
      title: "ğŸ‰ Seasoned Senpai"
      description: "You're watching anime comfortably, picking up subtleties in dialogue and story. ğŸ‰"
    - points: 30000
      title: "âš¡ Dialogue Dynamo"
      description: "You understand complex dialogues and cultural references, enjoying anime at a deeper level. âš¡"
    - points: 75000
      title: "âœ¨ Anime Aficionado"
      description: "You've developed a refined understanding of anime themes, character arcs, and underlying cultural subtleties. âœ¨"
    - points: 100000
      title: "ğŸŒŸ Otaku Overlord"
      description: "You've become an anime master, understanding every genre, plot twist, and character arc with ease! ğŸŒŸ"
    - points: 200000
      title: "ğŸ”¥ Anime God"
      description: "You have transcended mere fandom and become a true deity of anime, understanding every nuance and unraveling the deepest mysteries of every genre. Nothing escapes your divine vision! ğŸ”¥"

  Listening:
    - points: 1
      title: "ğŸ§ Language Listener"
      description: "You've begun listening to Japanese media , your ears are just getting warmed up! ğŸ§"
    - points: 100
      title: "ğŸµ Audio Adventurer"
      description: "Regular listening practice is paying off; you're understanding common phrases! ğŸµ"
    - points: 1000
      title: "ğŸ§ Dialogue Decoder"
      description: "You can understand spoken Japanese at a natural speed, grasping complex dialogues. ğŸ§"
    - points: 5000
      title: "ğŸ¼ Sound Samurai"
      description: "You're a pro, understanding context, slang, and tone in any conversation! ğŸ¼"
    - points: 15000
      title: "ğŸ™ï¸ Conversational Conqueror"
      description: "You've reached a high level of listening comprehension, comfortably following fast-paced conversations. ğŸ™ï¸"
    - points: 50000
      title: "âœ¨ Auditory Expert"
      description: "Your listening skills have reached a level where you can catch subtle tones and advanced expressions effortlessly. âœ¨"
    - points: 100000
      title: "ğŸŒŸ Auditory Ace"
      description: "You've achieved auditory mastery, effortlessly understanding every nuance of spoken Japanese. ğŸŒŸ"
    - points: 200000
      title: "ğŸ¶ God of Listening"
      description: "Your ears have ascended to a divine plane, capturing every syllable, tone, and hidden meaning with godly precision. The spoken word bows before you! ğŸ¶"

  Reading:
    - points: 1
      title: "ğŸ“„ Character Catcher"
      description: "You've started recognizing Japanese characters. The reading journey begins! ğŸ“„"
    - points: 500
      title: "ğŸ”¤ Kana Connoisseur"
      description: "You're getting more familiar with kana, building reading confidence. ğŸ”¤"
    - points: 2000
      title: "ğŸˆ¶ Vocabulary Voyager"
      description: "You can read common words and phrases across various texts! ğŸˆ¶"
    - points: 10000
      title: "ç©º Kanji Keeper"
      description: "Comfortable with kanji, you're reading intermediate texts with ease! ç©º"
    - points: 30000
      title: "ğŸ“š Script Scholar"
      description: "You're comfortable with a wide range of kanji, reading advanced texts smoothly. ğŸ“š"
    - points: 75000
      title: "âœ¨ Text Tactician"
      description: "You navigate advanced Japanese texts, understanding complex vocabulary and contextual nuances. âœ¨"
    - points: 100000
      title: "ğŸ‘‘ Script Shogun"
      description: "You've reached the highest level of reading mastery, easily navigating native texts of all kinds. ğŸ‘‘"
    - points: 200000
      title: "ğŸ“œ God of Reading"
      description: "You've reached divine comprehension, able to read and understand every character, kanji, and cultural reference as if it were second nature. The written word bends to your will! ğŸ“œ"
