# No guild specific settings required.
role_ids_to_ignore:
  - 1300745834232680448 # Janitor
  - 1294661079032528948 # Full-Selfmute
  - 1294660039747047425 # Selfmute
  - 780869751995629589 # VN Club
  - 839630698867720232 # Novel Club
  - 1137477094025220116 # Reading Sessions
  - 809103911298138152 # Manga Club
  - 908060451856855120 # 3D Club
  - 893158756333015100 # Video Game Club
  - 817235260105424946 # Anime Club
  - 901164969557639228 # Joseimuke Club
  - 1091433670868488252 # Cooking Club
  - 1129470266779643915 # JLPT Group
  - 1137477005865123840 # VC Group
  - 1297383002849935456 # Testing Guild: Admin

announce_channel:
  617136488840429598: 617136489482027059
  1297383002610995272: 1297383003479081019
